public with sharing class IterationRecipes {

    private Account account = null;

    public static List<String> iterableApiClientRecipe() {
        List<String> records = new List<String>();
        return records;
    } 

    public static ArrayList<String> iterableApiClientRecipe() {
        // Some some = null;
        return null;
    }

    public static ArrayList<Integer> iterableApiClientRecipe( Set<String> set ) {
        return null;
    }
}
